[phases.setup]
nixPkgs = ["python310", "gcc", "g++"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python rag.py"]

[start]
cmd = "uvicorn api:app --host 0.0.0.0 --port $PORT"
